FROM citusdata/membership-manager:0.3.0

# Обновляем pip и устанавливаем совместимую версию docker библиотеки
RUN pip install --upgrade pip \
    && pip uninstall -y docker docker-py \
    && pip install docker==5.0.3  # 👈 Используем версию 5.0.3, которая стабильнее работает с API

# Устанавливаем переменную окружения
ENV DOCKER_API_VERSION=1.44
ENV DOCKER_HOST=unix:///var/run/docker.sock